### ISSUE TITLE
change single file upload to any in form data

### ISSUE THREAD

**Issue by sahand-zeynol** [jmcdo29/nest-samples#7]
Hi
you can use any method in multer to get any file in controller.

**Comment by jmcdo29** [comment]
That would be use of the `AnyFilesInterceptor` right?

**Comment by sahand-zeynol** [comment]
yes!
I will be glad if you answer my [question](https://stackoverflow.com/questions/71198822/upload-dynamic-multiple-files-in-nestjs) too
thank you.
